### ISSUE TITLE
Uncaught ReferenceError: dimple is not defined

### ISSUE THREAD

**Issue by felipebueno** [sergeyt/meteor-dimple#3]
Hi, @sergeyt 

```
Uncaught ReferenceError: dimple is not defined 
```

Version 2.1.0

**Comment by felipebueno** [comment]
Hmm version 1.1.5 seems to be ok.

**Comment by sergeyt** [comment]
@felipebueno I've fixed the issue with resolving of d3 dependency required for dimple and released v2.1.0_1, sorry for delay.
